MODEL:
  DROP_PATH_RATE: 0.1
  ATTN_DROP: 0.0
  RELATIVE_POS: True
  SWIN:
    EMBED_DIM: 96
    NUM_DEPTHS: [ 1, 1, 3, 1 ]
    NUM_HEADS: [ 3, 6, 12, 24]
    WINDOW_SIZE: (7, 7)
    NUM_STAGES: 4
    PATCH_SIZE: 4
    NORM_LAYER: keras.layers.LayerNormalization
    QKV_BIAS: True
    QK_SCALE: None
    MLP_DROP: 0.0
    
    
DATA:
  IMG_SIZE: (224, 224)
  NUM_CLASSES: 200
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 1
  BASE_LR: 1e-04
  WARMUP_LR: 5e-07
  MIN_LR: 5e-06
  BATCH_SIZE: 16
  LR_SCHEDULER: 
    NAME: 'cosine'
  
